### ISSUE TITLE
Schematic review - v1.1

### ISSUE THREAD

**Issue by kaolpr** [sinara-hw/SiLPA_HL#24]
Use this issue for small corrections required for schematics. List them as tasks list. If a more complex problem is noticed feel free to create a new issue.

**Comment by skuchars** [comment]
- [x] #2 - it has already been done in first version, now I only organized schematic SiLPA_CPCIS_Con_P1_P6
- [x] #5 
- [x] #6 
- [x] #7 - these capacitors were placed wrongly on board, but they exist on schematic, so that is only a layout issue
- [x] #8 
- [x] #10 - added diode as @kaolpr suggested
- [x] #11
- [x] #12

**Comment by skuchars** [comment]
- [x] #13 
- [x] #14 
- [x] #16
- [x] #17
- [ ] #18 
- [x] #20 
- [x] #21
- [x] #26

**Comment by skuchars** [comment]
- [x] #29

**Comment by skuchars** [comment]
![image](https://github.com/sinara-hw/SiLPA_HL/assets/84103684/a9f67774-c0f5-4f76-842f-ed8356c84701)

**Comment by gkasprow** [comment]
@skuchars whare are you with layout?

**Comment by skuchars** [comment]
I have been doing it bit by bit for some time, but I can maximize effort now so hopefully I could finish most of the issues in few days time; then I will make a commit. But still any of my schematic changes weren't actually approved so it would be great if that can happen soon, for example by @kaolpr.

**Comment by skuchars** [comment]
@gkasprow

**Comment by gkasprow** [comment]
pls make sure you follow the newest DIOT template
https://github.com/sinara-hw/DIOT-Template/issues/1

**Comment by skuchars** [comment]
Questions: 
1. In sequencing circuit posted in https://github.com/sinara-hw/meta/issues/91#issuecomment-2302802191 there are absent transistors T3 and T4, but they do appear in the newest DIOT template. Which version should I implement, probably the newer one? 
2. In LVDS schematic IC32 is fully used (all sub-parts, A-D), was this intentional or I can drop this design and copy new DIOT template (only A B sub-parts in use)?

**Comment by gkasprow** [comment]
1. yes
2. it's better to use all parts, this lowers RDSon

**Comment by gkasprow** [comment]
2. I fixed that in the template

**Comment by martafafara** [comment]
- [x] #3

**Comment by martafafara** [comment]
- [x] LD7 current is limited only by T5 RDSon
- [x] IC39 is obsolete (replacement: TLC55IDR)
- [x] The O-ring connection at P3V3MP - used diodes could lead to power losses. Maybe ideal diode instead?
- [ ] No variants for EEM and DIOT as requiered in [DIOT Template](https://github.com/sinara-hw/DIOT-Template/issues/1)
- [x] 3 fiducials per site is more convenient
- [x] schematic sheets need to be numbered
- [x] IC26 and IC27 are obsolete
- [x] take into account #3 

@skuchars @gkasprow

**Comment by skuchars** [comment]
IC39 TLC55ID -> TLC55IDR  
IC26, IC27 LM75AIMM/NOPB -> LM75AIMMX/NOPB

@martafafara can you elaborate point 4, about P3V3MP? Because I'm not sure I understand it correctly, do you want to change D5?

**Comment by martafafara** [comment]
The O-ring connection occurs where the system is powered up by more than one power supply, any redundant to each other. In case of SILPA_HL D5 protects IC5 if P3V3P out of EEM connectors are used. But on the other hand if IC5 is the voltage source, the voltage drop occurs at D5. Due to this fact you could consider to replace discrete D5 diode with ideal diode circuit. Some info about differences you can find [here](https://product.torexsemi.com/en/technical-support/techfaq/doc_4261). 
In this particular project no high currents are predicted, so power losses are not so important, but the decreased voltage level could not be accepted by all circuits. Please, ensure if everything keeps the requirements.

**Comment by skuchars** [comment]
Thank you for your explanation. I propose LM66100DCKR, it fits our parameters (1.5V to 5.5V VDD, up to 1.5A), it's readily available (Mouser has 17k of them in stock currently), small and easy to replace if needed (SC70-6 package).

**Comment by martafafara** [comment]
It seems to be appropriate solution. Waiting for new commit.

**Comment by martafafara** [comment]
- [ ] According to LM66100DCKR - ST pin should rather be pulled up to VOUT than short-circuited to the ground. It's the output pin that could generate unnecessary EMI problems.
- [ ] No variatns are predicted

@skuchars May I start with layout review?

**Comment by skuchars** [comment]
<img width="1582" height="71" alt="Image" src="https://github.com/user-attachments/assets/19450dcc-bf0b-44b4-9f09-10c5ccc57b49" />
Are you sure? Datasheet says to connect it to ground if not used.
 
Yes, you can start with layout review.

**Comment by martafafara** [comment]
You are right. Typical application schematics, figure 13 and so on misled me.
